apiVersion: hhiroshell.github.com
kind: SedTransformer
metadata:
  name: replace-foo-with-bar
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ../plugins/sedtransformer.sh
spec:
  replacements:
    foo: bar